name: TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update TryHackMe badge
        uses: nahilr/tryhackme-profile-badge-workflow@main
        with:
          user_public_id: 
